// Code generated by ent, DO NOT EDIT.

package apiconfig

const (
	// Label holds the string label denoting the apiconfig type in the database.
	Label = "api_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the apiconfig in the database.
	Table = "api_configs"
)

// Columns holds all SQL columns for apiconfig fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
