// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIConfigsColumns holds the columns for the "api_configs" table.
	APIConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// APIConfigsTable holds the schema information for the "api_configs" table.
	APIConfigsTable = &schema.Table{
		Name:       "api_configs",
		Columns:    APIConfigsColumns,
		PrimaryKey: []*schema.Column{APIConfigsColumns[0]},
	}
	// TaxonomyVocabulariesColumns holds the columns for the "taxonomy_vocabularies" table.
	TaxonomyVocabulariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "vid", Type: field.TypeString, Unique: true},
		{Name: "label", Type: field.TypeString},
		{Name: "weight", Type: field.TypeInt, Default: 0},
		{Name: "description", Type: field.TypeString},
	}
	// TaxonomyVocabulariesTable holds the schema information for the "taxonomy_vocabularies" table.
	TaxonomyVocabulariesTable = &schema.Table{
		Name:       "taxonomy_vocabularies",
		Columns:    TaxonomyVocabulariesColumns,
		PrimaryKey: []*schema.Column{TaxonomyVocabulariesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIConfigsTable,
		TaxonomyVocabulariesTable,
	}
)

func init() {
}
