// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/oaktreecode/oakapi/ent/schema"
	"github.com/oaktreecode/oakapi/ent/taxonomyvocabulary"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taxonomyvocabularyFields := schema.TaxonomyVocabulary{}.Fields()
	_ = taxonomyvocabularyFields
	// taxonomyvocabularyDescVid is the schema descriptor for vid field.
	taxonomyvocabularyDescVid := taxonomyvocabularyFields[0].Descriptor()
	// taxonomyvocabulary.VidValidator is a validator for the "vid" field. It is called by the builders before save.
	taxonomyvocabulary.VidValidator = taxonomyvocabularyDescVid.Validators[0].(func(string) error)
	// taxonomyvocabularyDescLabel is the schema descriptor for label field.
	taxonomyvocabularyDescLabel := taxonomyvocabularyFields[1].Descriptor()
	// taxonomyvocabulary.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	taxonomyvocabulary.LabelValidator = taxonomyvocabularyDescLabel.Validators[0].(func(string) error)
	// taxonomyvocabularyDescWeight is the schema descriptor for weight field.
	taxonomyvocabularyDescWeight := taxonomyvocabularyFields[2].Descriptor()
	// taxonomyvocabulary.DefaultWeight holds the default value on creation for the weight field.
	taxonomyvocabulary.DefaultWeight = taxonomyvocabularyDescWeight.Default.(int)
	// taxonomyvocabularyDescID is the schema descriptor for id field.
	taxonomyvocabularyDescID := taxonomyvocabularyFields[4].Descriptor()
	// taxonomyvocabulary.DefaultID holds the default value on creation for the id field.
	taxonomyvocabulary.DefaultID = taxonomyvocabularyDescID.Default.(func() uuid.UUID)
}
