// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/oaktreecode/oakapi/ent/predicate"
	"github.com/oaktreecode/oakapi/ent/taxonomyvocabulary"
)

// TaxonomyVocabularyQuery is the builder for querying TaxonomyVocabulary entities.
type TaxonomyVocabularyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TaxonomyVocabulary
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaxonomyVocabularyQuery builder.
func (tvq *TaxonomyVocabularyQuery) Where(ps ...predicate.TaxonomyVocabulary) *TaxonomyVocabularyQuery {
	tvq.predicates = append(tvq.predicates, ps...)
	return tvq
}

// Limit adds a limit step to the query.
func (tvq *TaxonomyVocabularyQuery) Limit(limit int) *TaxonomyVocabularyQuery {
	tvq.limit = &limit
	return tvq
}

// Offset adds an offset step to the query.
func (tvq *TaxonomyVocabularyQuery) Offset(offset int) *TaxonomyVocabularyQuery {
	tvq.offset = &offset
	return tvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tvq *TaxonomyVocabularyQuery) Unique(unique bool) *TaxonomyVocabularyQuery {
	tvq.unique = &unique
	return tvq
}

// Order adds an order step to the query.
func (tvq *TaxonomyVocabularyQuery) Order(o ...OrderFunc) *TaxonomyVocabularyQuery {
	tvq.order = append(tvq.order, o...)
	return tvq
}

// First returns the first TaxonomyVocabulary entity from the query.
// Returns a *NotFoundError when no TaxonomyVocabulary was found.
func (tvq *TaxonomyVocabularyQuery) First(ctx context.Context) (*TaxonomyVocabulary, error) {
	nodes, err := tvq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{taxonomyvocabulary.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tvq *TaxonomyVocabularyQuery) FirstX(ctx context.Context) *TaxonomyVocabulary {
	node, err := tvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaxonomyVocabulary ID from the query.
// Returns a *NotFoundError when no TaxonomyVocabulary ID was found.
func (tvq *TaxonomyVocabularyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tvq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{taxonomyvocabulary.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tvq *TaxonomyVocabularyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaxonomyVocabulary entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaxonomyVocabulary entity is found.
// Returns a *NotFoundError when no TaxonomyVocabulary entities are found.
func (tvq *TaxonomyVocabularyQuery) Only(ctx context.Context) (*TaxonomyVocabulary, error) {
	nodes, err := tvq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{taxonomyvocabulary.Label}
	default:
		return nil, &NotSingularError{taxonomyvocabulary.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tvq *TaxonomyVocabularyQuery) OnlyX(ctx context.Context) *TaxonomyVocabulary {
	node, err := tvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaxonomyVocabulary ID in the query.
// Returns a *NotSingularError when more than one TaxonomyVocabulary ID is found.
// Returns a *NotFoundError when no entities are found.
func (tvq *TaxonomyVocabularyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tvq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{taxonomyvocabulary.Label}
	default:
		err = &NotSingularError{taxonomyvocabulary.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tvq *TaxonomyVocabularyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaxonomyVocabularies.
func (tvq *TaxonomyVocabularyQuery) All(ctx context.Context) ([]*TaxonomyVocabulary, error) {
	if err := tvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tvq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tvq *TaxonomyVocabularyQuery) AllX(ctx context.Context) []*TaxonomyVocabulary {
	nodes, err := tvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaxonomyVocabulary IDs.
func (tvq *TaxonomyVocabularyQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := tvq.Select(taxonomyvocabulary.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tvq *TaxonomyVocabularyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tvq *TaxonomyVocabularyQuery) Count(ctx context.Context) (int, error) {
	if err := tvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tvq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tvq *TaxonomyVocabularyQuery) CountX(ctx context.Context) int {
	count, err := tvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tvq *TaxonomyVocabularyQuery) Exist(ctx context.Context) (bool, error) {
	if err := tvq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tvq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tvq *TaxonomyVocabularyQuery) ExistX(ctx context.Context) bool {
	exist, err := tvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaxonomyVocabularyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tvq *TaxonomyVocabularyQuery) Clone() *TaxonomyVocabularyQuery {
	if tvq == nil {
		return nil
	}
	return &TaxonomyVocabularyQuery{
		config:     tvq.config,
		limit:      tvq.limit,
		offset:     tvq.offset,
		order:      append([]OrderFunc{}, tvq.order...),
		predicates: append([]predicate.TaxonomyVocabulary{}, tvq.predicates...),
		// clone intermediate query.
		sql:    tvq.sql.Clone(),
		path:   tvq.path,
		unique: tvq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Vid string `json:"vid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaxonomyVocabulary.Query().
//		GroupBy(taxonomyvocabulary.FieldVid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tvq *TaxonomyVocabularyQuery) GroupBy(field string, fields ...string) *TaxonomyVocabularyGroupBy {
	grbuild := &TaxonomyVocabularyGroupBy{config: tvq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tvq.sqlQuery(ctx), nil
	}
	grbuild.label = taxonomyvocabulary.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Vid string `json:"vid,omitempty"`
//	}
//
//	client.TaxonomyVocabulary.Query().
//		Select(taxonomyvocabulary.FieldVid).
//		Scan(ctx, &v)
//
func (tvq *TaxonomyVocabularyQuery) Select(fields ...string) *TaxonomyVocabularySelect {
	tvq.fields = append(tvq.fields, fields...)
	selbuild := &TaxonomyVocabularySelect{TaxonomyVocabularyQuery: tvq}
	selbuild.label = taxonomyvocabulary.Label
	selbuild.flds, selbuild.scan = &tvq.fields, selbuild.Scan
	return selbuild
}

func (tvq *TaxonomyVocabularyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tvq.fields {
		if !taxonomyvocabulary.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tvq.path != nil {
		prev, err := tvq.path(ctx)
		if err != nil {
			return err
		}
		tvq.sql = prev
	}
	return nil
}

func (tvq *TaxonomyVocabularyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TaxonomyVocabulary, error) {
	var (
		nodes = []*TaxonomyVocabulary{}
		_spec = tvq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*TaxonomyVocabulary).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &TaxonomyVocabulary{config: tvq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tvq *TaxonomyVocabularyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tvq.querySpec()
	_spec.Node.Columns = tvq.fields
	if len(tvq.fields) > 0 {
		_spec.Unique = tvq.unique != nil && *tvq.unique
	}
	return sqlgraph.CountNodes(ctx, tvq.driver, _spec)
}

func (tvq *TaxonomyVocabularyQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tvq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tvq *TaxonomyVocabularyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   taxonomyvocabulary.Table,
			Columns: taxonomyvocabulary.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: taxonomyvocabulary.FieldID,
			},
		},
		From:   tvq.sql,
		Unique: true,
	}
	if unique := tvq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tvq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taxonomyvocabulary.FieldID)
		for i := range fields {
			if fields[i] != taxonomyvocabulary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tvq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tvq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tvq *TaxonomyVocabularyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tvq.driver.Dialect())
	t1 := builder.Table(taxonomyvocabulary.Table)
	columns := tvq.fields
	if len(columns) == 0 {
		columns = taxonomyvocabulary.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tvq.sql != nil {
		selector = tvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tvq.unique != nil && *tvq.unique {
		selector.Distinct()
	}
	for _, p := range tvq.predicates {
		p(selector)
	}
	for _, p := range tvq.order {
		p(selector)
	}
	if offset := tvq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tvq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TaxonomyVocabularyGroupBy is the group-by builder for TaxonomyVocabulary entities.
type TaxonomyVocabularyGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tvgb *TaxonomyVocabularyGroupBy) Aggregate(fns ...AggregateFunc) *TaxonomyVocabularyGroupBy {
	tvgb.fns = append(tvgb.fns, fns...)
	return tvgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tvgb *TaxonomyVocabularyGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tvgb.path(ctx)
	if err != nil {
		return err
	}
	tvgb.sql = query
	return tvgb.sqlScan(ctx, v)
}

func (tvgb *TaxonomyVocabularyGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tvgb.fields {
		if !taxonomyvocabulary.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tvgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tvgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tvgb *TaxonomyVocabularyGroupBy) sqlQuery() *sql.Selector {
	selector := tvgb.sql.Select()
	aggregation := make([]string, 0, len(tvgb.fns))
	for _, fn := range tvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tvgb.fields)+len(tvgb.fns))
		for _, f := range tvgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tvgb.fields...)...)
}

// TaxonomyVocabularySelect is the builder for selecting fields of TaxonomyVocabulary entities.
type TaxonomyVocabularySelect struct {
	*TaxonomyVocabularyQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tvs *TaxonomyVocabularySelect) Scan(ctx context.Context, v interface{}) error {
	if err := tvs.prepareQuery(ctx); err != nil {
		return err
	}
	tvs.sql = tvs.TaxonomyVocabularyQuery.sqlQuery(ctx)
	return tvs.sqlScan(ctx, v)
}

func (tvs *TaxonomyVocabularySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tvs.sql.Query()
	if err := tvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
