// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oaktreecode/oakapi/ent/predicate"
	"github.com/oaktreecode/oakapi/ent/taxonomyvocabulary"
)

// TaxonomyVocabularyDelete is the builder for deleting a TaxonomyVocabulary entity.
type TaxonomyVocabularyDelete struct {
	config
	hooks    []Hook
	mutation *TaxonomyVocabularyMutation
}

// Where appends a list predicates to the TaxonomyVocabularyDelete builder.
func (tvd *TaxonomyVocabularyDelete) Where(ps ...predicate.TaxonomyVocabulary) *TaxonomyVocabularyDelete {
	tvd.mutation.Where(ps...)
	return tvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tvd *TaxonomyVocabularyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tvd.hooks) == 0 {
		affected, err = tvd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TaxonomyVocabularyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tvd.mutation = mutation
			affected, err = tvd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tvd.hooks) - 1; i >= 0; i-- {
			if tvd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tvd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tvd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tvd *TaxonomyVocabularyDelete) ExecX(ctx context.Context) int {
	n, err := tvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tvd *TaxonomyVocabularyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: taxonomyvocabulary.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: taxonomyvocabulary.FieldID,
			},
		},
	}
	if ps := tvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// TaxonomyVocabularyDeleteOne is the builder for deleting a single TaxonomyVocabulary entity.
type TaxonomyVocabularyDeleteOne struct {
	tvd *TaxonomyVocabularyDelete
}

// Exec executes the deletion query.
func (tvdo *TaxonomyVocabularyDeleteOne) Exec(ctx context.Context) error {
	n, err := tvdo.tvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taxonomyvocabulary.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tvdo *TaxonomyVocabularyDeleteOne) ExecX(ctx context.Context) {
	tvdo.tvd.ExecX(ctx)
}
