// Code generated by ent, DO NOT EDIT.

package taxonomyvocabulary

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the taxonomyvocabulary type in the database.
	Label = "taxonomy_vocabulary"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVid holds the string denoting the vid field in the database.
	FieldVid = "vid"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// Table holds the table name of the taxonomyvocabulary in the database.
	Table = "taxonomy_vocabularies"
)

// Columns holds all SQL columns for taxonomyvocabulary fields.
var Columns = []string{
	FieldID,
	FieldVid,
	FieldLabel,
	FieldWeight,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// VidValidator is a validator for the "vid" field. It is called by the builders before save.
	VidValidator func(string) error
	// LabelValidator is a validator for the "label" field. It is called by the builders before save.
	LabelValidator func(string) error
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
