// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApiConfig is the predicate function for apiconfig builders.
type ApiConfig func(*sql.Selector)

// TaxonomyVocabulary is the predicate function for taxonomyvocabulary builders.
type TaxonomyVocabulary func(*sql.Selector)
